title: yelp-fusion-client
email: stewart.s.seo.@gmailcom
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "/yelp-fusion-client" # the subpath of your site, e.g. /blog
url: "https://stewseo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  stewseo

# Build settings
remote_theme: pmarsceill/just-the-docs

color_scheme: dark

plugins:
  - github-pages
  - jekyll-remote-theme
